Add number entities for battery soc reserve
cdpuk/givenergy-local pull request #46
Opened 2023-04-16 09:47 UTC by reidjr

Changes to number.py only. I have never contributed through github before, so not sure about protocol for changes to pull requests, so created new one.

2023-04-27 21:11 UTC, cdpuk commented on custom_components/givenergy_local/number.py
> +        # self._attr_native_step = 5
Commented out code - uncommenting this line would be the simplest approach, and it keeps the sliders working in a consistent way. Note that it's purely for slider usability; a service call can set any value if required.

2023-04-27 21:13 UTC, cdpuk requested changes
Just the commented out code to deal with.

I'm going to ignore the failing test - there's been an update to the test framework that I'm looking at separately.

2023-04-27 21:40 UTC, reidjr commented
Done and Done. I was worried about 5% steps starting at 4% .....

2023-04-28 06:24 UTC, reidjr commented on custom_components/givenergy_local/number.py
> +        # self._attr_native_step = 5
Done

2023-04-28 16:29 UTC, merged